### ISSUE TITLE
FAQ - Is the data in the RDM system being backed up? 

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdm-wiki#37]
There is a mirror copy of all data in the RDM system. This protects against file corruptions and hardware failures, but not against human errors. Files that are overwritten or deleted by researchers in the RDM system are also overwritten or deleted in the mirror copy.

**Comment by robertoostenveld** [comment]
this was again raised by the security officer in a meeting including me and @EricMaris. Eric mentioned that there is a few day backup, probably with isilon snapshots. This needs to be clarified and documented.

**Comment by robertoostenveld** [comment]
@hurngchunlee can you document on intranet what the backup policy is of the DRDR system? I suggest to include it on https://intranet.donders.ru.nl/index.php?id=4728

**Comment by robertoostenveld** [comment]
hi @hurngchunlee, any plans to document the backup policy? If not, then please also close this issue.

**Comment by robertoostenveld** [comment]
hi @hurngchunlee, any plans to document the backup policy? If not, then please also close this issue.

**Comment by robertoostenveld** [comment]
hi @hurngchunlee, any plans to document the backup policy? If not, then please also close this issue.

**Comment by robertoostenveld** [comment]
hi @hurngchunlee, any plans to document the backup policy? If not, then please also close this issue.

**Comment by hurngchunlee** [comment]
There is no plan for backup. Closing it.

**Comment by robertoostenveld** [comment]
the question was not about the backup itself, but about documenting this as FAQ. It is a topic that researchers need to address in their data management plans.
